import joblib
import pandas as pd
import sys
import os

# ==========================
# FIX IMPORT PATH
# ==========================
sys.path.append(os.path.abspath("."))

from utils.recommendation import get_recommendation

# ==========================
# LOAD MODELS
# ==========================
soh_model = joblib.load("models/soh_model.pkl")
rul_model = joblib.load("models/rul_model.pkl")

# ==========================
# SAMPLE BATTERY INPUT
# ==========================
sample = {
    "IR": 0.017,
    "QCharge": 1.05,
    "QDischarge": 1.03,
    "Tavg": 32,
    "Tmax": 35,
    "Tmin": 29,
    "chargetime": 13.2,
    "cycle": 600
}

# ==========================
# CREATE DATAFRAME
# ==========================
df = pd.DataFrame([sample])

# ==========================
# PREDICT SOH
# ==========================
soh = soh_model.predict(df)[0]

# ==========================
# PREDICT RUL
# ==========================
rul = rul_model.predict(df)[0]

# ==========================
# GET RECOMMENDATION
# ==========================
recommendation = get_recommendation(soh, rul)

# ==========================
# ASSIGN GRADE
# ==========================
if soh >= 90:
    grade = "A"
    health_status = "Excellent"

elif soh >= 80:
    grade = "B"
    health_status = "Good"

elif soh >= 70:
    grade = "C"
    health_status = "Moderate"

else:
    grade = "D"
    health_status = "Poor"

# ==========================
# BATTERY ID
# ==========================
battery_id = "BATT-001"

# ==========================
# PRINT PASSPORT
# ==========================
print("\n" + "=" * 55)
print("           SECONDSPARK BATTERY PASSPORT")
print("=" * 55)

print(f"\nBattery ID         : {battery_id}")

print("\n----- HEALTH METRICS -----")
print(f"SOH                : {soh:.2f}%")
print(f"RUL                : {rul:.0f} Cycles")

print("\n----- HEALTH ASSESSMENT -----")
print(f"Battery Grade      : {grade}")
print(f"Health Status      : {health_status}")

print("\n----- RECOMMENDATION -----")
print(f"{recommendation}")

print("\n" + "=" * 55)
print("Generated by SecondSpark AI")
print("=" * 55)